---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eltg1461/public_html/iptul.my.id/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f index.php $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
    - /bin/cp -f og.png $DEPLOYPATH
    - /bin/cp -rf games $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/index.html $DEPLOYPATH/index.php $DEPLOYPATH/.htaccess $DEPLOYPATH/og.png
    - /usr/bin/find $DEPLOYPATH/games -type d -exec /bin/chmod 755 {} +
    - /usr/bin/find $DEPLOYPATH/games -type f -exec /bin/chmod 644 {} +
