---
deployment:
  tasks:
    - export DEPLOYPATH=/home/eltg1461/public_html/iptul.my.id/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f index.php $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/index.html $DEPLOYPATH/index.php $DEPLOYPATH/.htaccess
